# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 03:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_employee_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edu_name', models.CharField(max_length=50)),
                ('edu_type', models.CharField(max_length=50)),
                ('edu_uni', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'emp_education',
            },
        ),
        migrations.AlterField(
            model_name='employee',
            name='emp_email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='Employee',
        ),
        migrations.AddField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Employee'),
        ),
    ]
