# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-08 15:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20180708_0308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='crud.Employee'),
        ),
    ]
